backend:
  name: git-gateway

media_folder: "assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    format: "json"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
